# Generated by Django 2.1.3 on 2019-01-10 19:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190110_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 10, 19, 10, 54, 900022, tzinfo=utc)),
        ),
    ]
